articles/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url

# Импортируем классы для отображения записей.
# Это так называемые class based generic views
from django.views.generic import DetailView, ListView

# Пока мы этот класс представления не создали, но создадим позже
from .views import ArticleListView, ArticleDetailView, ArticleCategoryListView

urlpatterns = patterns('',

    # Показываем список всех статей
    url(r'^$', ArticleListView.as_view(), 
        name="article_list"
    ),

    # Показываем детально статью
    url(r'^(?P<pk>\d+)/$', ArticleDetailView.as_view(), 
        name="article_detail"
    ),

    # Показываем список всех статей категории
    url(r'^(?P<slug>\w+)/$', ArticleCategoryListView.as_view(), 
        name="article_category_list"
    ),
    
)

pages/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url

# Импортируем классы для отображения записей.
# Это так называемые class based generic views
from django.views.generic import DetailView, ListView

from .views import PageListView, PageDetailView

urlpatterns = patterns('',

    # Показываем список всех статей
    url(r'^$', PageListView.as_view(), 
        name="page_list"
    ),

    # Показываем детально статью
    url(r'^(?P<pk>[0-9]+)/$', PageDetailView.as_view(), 
        name="page_detail_id"
    ),

    # Показываем детально статью
    url(r'^(?P<slug>\w+)/$', PageDetailView.as_view(), 
        name="page_detail"
    ),

)

thesame/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()
from .views import IndexView, ContactsView


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thesame.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('articles.urls', namespace='articles')),

    # Форма обратной связи
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^contacts/', ContactsView.as_view(), name='contacts'),

    url(r'^', include('pages.urls')),
 
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(r'(?:.*?/)?(?P<path>(css|jquery|js|images)/.+)$', document_root=settings.STATIC_ROOT)

articles/models.py
# -*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.SlugField(verbose_name='Идентификатор')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Article(models.Model):
    pic = models.ImageField(upload_to='uploads/articles')
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    author = models.ManyToManyField(User)
    content = models.TextField(verbose_name='Содержание')
    category = models.ManyToManyField(Category, verbose_name=u'Категория')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

articles/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Article


class ArticleListView(ListView):
    # Название переменной, которая будет содержать список записей
    context_object_name = 'article_list'
    # Имя шаблона для вывода списка (еще не создали)
    template_name = 'articles/article_list.html'

    def get_queryset(self):
        articles = Article.objects.all()
        paginator = Paginator(articles, 2)
        page = self.request.GET.get('page')
        try:
            articles = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            articles = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            articles = paginator.page(paginator.num_pages)
        return articles

class ArticleDetailView(DetailView):

    model = Article
    context_object_name = 'article'
    template_name = 'articles/article_detail.html'


# Наследуем функционал уже существующего класса, 
# который выводит список всех статей
class ArticleCategoryListView(ArticleListView):

    # Изменяем запрос, чтобы получить только статьи определенной категории
    def get_queryset(self):
        return Article.objects.filter(category__slug=self.kwargs['slug'])

articles/templates/articles/article_detail.html
{% extends 'articles_base.html' %}

{% load articles_extras %}
{% load thumbnail %}
{% load threadedcomments_tags %}
{% load staticfiles %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'js/comments.js' %}"></script>
{% endblock %}

{% block article_content %}
    <article class="article">
        {% article_short article %}
        <h1>{{ article.title }}</h1>
        {{ article.content|safe }}

        {% render_comment_list for article %}
        {% render_comment_form for article %}

        <!--
        <div id="wrap_write_comment">
            <div id="form-comment">
                {% get_comment_form for article as form %}
                <form action="/comments/post/" method="post">{% csrf_token %}
                    {{ form.as_p }}{# just to keep the example simple. Consider using django-crispy-forms in real life #}

                    <p>
                      <input type="submit" value="Submit Comment"/>
                      <a href="#c0" id="cancel_reply">cancel reply</a>
                    </p>
                </form>
            </div>
        </div> -->

    </article>
{% endblock %}
       

articles/templates/articles/article_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% load articles_extras %}
{% load blocks_extras %}

{% block content %}

    <h1 class="page_title">Blog</h1>

    <div class="breadcrumbs">
        <div class="inside">
            <a class="first" href="/"><span>Главная</span></a>
            <a class="last last-child" href="{% url 'articles:article_list' %}"><span>Блог</span></a>
        </div>
    </div>

    <div class="columns">
        <div class="column column75">
            {% for article in article_list %}
                <article class="article">   
                    {% article_short article %}
                    <h1>{{ article.title }}</h1>
                    {{ article.content|safe }}
                    
                    <a class="button button_small button_orange float_left" 
                        href="{% url 'articles:article_detail' article.id %}">
                        <span class="inside">Подробнее</span>
                    </a>
                </article>
            {% endfor %}

            

            <div class="pagination">

                {% if article_list.has_previous %}
                    <a href="?page={{ article_list.previous_page_number }}">&larr;</a>
                {% endif %}

                {% for num in article_list.paginator.page_range %}
                    {% if num == article_list.number %}
                        <span class="current"><b>{{ num }}</b></span>
                    {% else %}
                        <a href="?page={{ num }}"> {{ num }}</a>
                    {% endif %} 
                {% endfor %}

                {% if article_list.has_next %}
                    <a href="?page={{ article_list.next_page_number }}">&rarr;</a>
                {% endif %}

            </div>

        </div>
        
        <div class="column column25">
            <div class="padd16bot">
                <h1>Search</h1>
                <form class="searchbar">
                <fieldset>
                    <div>
                        <span class="input_text"><input type="text" value="Search..." class="clearinput"></span>
                        <button class="input_submit" type="button"><span>Search</span></button> 
                    </div>
                </fieldset>
                </form>
            </div>

            <div class="padd16bot">
                <h1>Recent Posts</h1>
                <ul class="recent_posts">
                    {% block posts_list_recent %}
                        {% for article in articles_list_recent %}
                            {% article_recent article %}
                        {% endfor %}
                    {% endblock %}
                </ul>   
            </div>
            
            <div class="padd16bot">
                {% show_block 'about_us' %}
            </div>
            
            <div class="padd16bot">
                <h1>Categories</h1>
                <ul class="menu categories page_text">
                    <li><a href="#">Webdesign (8)</a></li>
                    <li>
                        <a href="#">Branding (12)</a>
                        <ul>
                            <li><a href="#">Photography (45)</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Photomanipulation (5)</a></li>
                    <li><a href="#">3D (1)</a></li>
                    <li><a href="#">Others (7)</a></li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}