feedback/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from .views import FeedbackCreate, FeedbackSuccess

urlpatterns = [
    url(r'^create/$', FeedbackCreate.as_view(), name='create'),
    url(r'^success/$', FeedbackSuccess.as_view(), name='success'),
    #url(r'^(?P<pk>[0-9]+)/$', AuthorUpdate.as_view(), name='author_update'),
    #url(r'^(?P<pk>[0-9]+)/delete/$', AuthorDelete.as_view(), name='author_delete'),
]

pages/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url

# Импортируем классы для отображения записей.
# Это так называемые class based generic views
from django.views.generic import DetailView, ListView

from .views import PageListView, PageDetailView

urlpatterns = patterns('',

    # Показываем список всех статей
    url(r'^$', PageListView.as_view(), 
        name="page_list"
    ),

    # Показываем детально статью
    url(r'^(?P<pk>[0-9]+)/$', PageDetailView.as_view(), 
        name="page_detail_id"
    ),

    # Показываем детально статью
    url(r'^(?P<slug>\w+)/$', PageDetailView.as_view(), 
        name="page_detail"
    ),

)

thesame/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()
from .views import IndexView, ContactsView


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'thesame.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('articles.urls', namespace='articles')),

    # Форма обратной связи
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^contacts/', ContactsView.as_view(), name='contacts'),

    url(r'^', include('pages.urls')),
 
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
+ static(r'(?:.*?/)?(?P<path>(css|jquery|js|images)/.+)$', document_root=settings.STATIC_ROOT)

feedback/models.py
# -*- coding:utf-8 -*-
from django.db import models

class Feedback(models.Model):
    subject = models.CharField(u'Тема', max_length=100)
    email = models.EmailField(u'Email', blank=True)
    message = models.TextField(u'Сообщение')
    added = models.DateTimeField(u'Создано', auto_now_add=True)

    def __unicode__(self):
        return self.subject

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратная связь'

feedback/forms.py
from django.forms import ModelForm
from .models import Feedback

class FeedbackForm(ModelForm):
    class Meta:
        model = Feedback

feedback/views.py
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from .models import Feedback


class FeedbackCreate(CreateView):
    model = Feedback
    success_url = reverse_lazy('feedback:success')


class FeedbackSuccess(TemplateView):
    template_name = 'feedback/feedback_success.html'


'''
class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')
'''

feedback/templates/feedback/feedback_form.html
<!-- <form action="{% url 'contacts' %}" method="post">
    {% for field in form %}
        {{ field.errors }}
        <p>    
            {{ field.label_tag }} {{ field }}
        </p>
    {% endfor %}
    {% csrf_token %}
    <p><input type="submit" value="Отправить" /></p>
</form> -->


<form method="post" class="contactform ajaxform" action="{% url 'contacts' %}">
    
    <div class="columns">

        <div class="column column25">
            
            {{ form.email.label_tag }}
            <span class="input_text">
                {{ form.email }}
                
            </span>
            {{ form.email.errors }}
        </div>

        <div class="column column25">
            {{ form.subject.label_tag }}
            <span class="input_text">
                {{ form.subject }}
                
            </span>
            {{ form.subject.errors }}
        </div>
    </div>
    <div class="columns">
            {{ form.message.label_tag }}
        <span class="input_textarea">
            {{ form.message }}
        </span>
        {{ form.message.errors }}
    </div>
    <button class="button_container" type="submit">
        <span class="button button_small button_orange">
            <span class="inside">Отправить</span>
        </span>
        
    </button>
    {% csrf_token %}
</form>

<!-- 
Подробное описание формы
<form action="/contact/" method="post">
    {{ form.non_field_errors }}
    <div class="fieldWrapper">
        {{ form.subject.errors }}
        <label for="id_subject">Email subject:</label>
        {{ form.subject }}
    </div>
    <div class="fieldWrapper">
        {{ form.message.errors }}
        <label for="id_message">Your message:</label>
        {{ form.message }}
    </div>
    <div class="fieldWrapper">
        {{ form.sender.errors }}
        <label for="id_sender">Your email address:</label>
        {{ form.sender }}
    </div>
    <div class="fieldWrapper">
        {{ form.cc_myself.errors }}
        <label for="id_cc_myself">CC yourself?</label>
        {{ form.cc_myself }}
    </div>
    <p><input type="submit" value="Send message" /></p>
</form>
-->

feedback/templates/feedback/feedback_success.html
{% extends 'base.html' %}

{% block content %}
<h2>Сообщение отправлено</h2>
<p>Спасибо Вам за обратную связь. Мы обязательно прочитаем ваше письмо.</p>
{% endblock %}